name: CI

on:
  push:
    paths:
      - "**.cs"
      - "**.csproj"
      - "**.sln"
      - "manifest.json"
  pull_request:
    paths:
      - "**.cs"
      - "**.csproj"
      - "**.sln"
      - "manifest.json"

permissions:
  contents: read

jobs:
  build:
    name: Compilation Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up .NET 8.0.x
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Add Stardew Valley reference assemblies
        uses: Pathoschild/SMAPI-ModBuildWorkflow/add-reference-assemblies@v0

      - name: Build (compilation check)
        run: dotnet build JojaAutoTasks.csproj -c Debug -p:EnableModDeploy=false -p:EnableModZip=false
